# Generated by Django 5.1 on 2025-09-27 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0003_rename_event_id_checkin_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='isMember',
            field=models.BooleanField(null=True),
        ),
    ]
