# Generated by Django 4.2.7 on 2024-02-18 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0002_entry_volunteer_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='volunteer_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='volunteer_task', to='volunteer.task'),
        ),
    ]
