# Generated by Django 4.2.7 on 2024-02-18 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0003_entry_volunteer_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='notes',
            field=models.CharField(blank=True, help_text='Did something noteworthy happen?', max_length=255, null=True),
        ),
    ]
