# Generated by Django 4.2.7 on 2024-03-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0004_alter_entry_active_alter_entry_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='mileage',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
