# Generated by Django 5.2.7 on 2025-12-07 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0005_alter_entry_mileage'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='meal',
            field=models.PositiveSmallIntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0, help_text='0 = no meal taken, 1 = meal taken'),
        ),
    ]
