# Generated by Django 4.2.7 on 2023-12-31 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_alter_customuser_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': (('is_kiosk_user', 'This account is for kiosk mode only.'),)},
        ),
    ]
