# Generated by Django 4.2.7 on 2023-12-31 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': (('is_kiosk_user', 'Kiosk mode only.'),)},
        ),
    ]
