# Generated by Django 4.2.7 on 2024-02-18 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_alter_customuser_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_active_date',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='member_since',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='quick_checkin',
        ),
    ]
